Prayer state update
Jonathanlau92/prayers-letterbox pull request #69
Opened 2020-08-13 15:30 UTC by TimothyHou

# Pull Request Description 

Task(s) you did:
add status update for prayers

How did you test it? : 
go to prayer edit page, change status, save it and see that it is saved.

Remarks:

2020-08-16 05:52 UTC, Jonathanlau92 requested changes

2020-08-16 05:52 UTC, Jonathanlau92 commented on app/webpacker/packs/application.js
> +            $("#change_status_prompt").html("<i>Why do you want to change status?</i>");
@TimothyHou The status prompt appears on the top instead of the status part of the form. I'll changed it and added bootstrap style

2020-08-16 05:52 UTC, Jonathanlau92 commented on app/webpacker/packs/application.js
> +    $('#prayer_status').selectize({
@TimothyHou oh can you put all the prayers related javascripts in an external js file? Can get very messy if all in application.js

2020-08-16 05:52 UTC, Jonathanlau92 commented on app/views/prayers/edit.html.erb
> +        <%= f.hidden_field :status, :id => 'curr_status' %>
@TimothyHou my prayer status is not updated with the new status. The POST request pass in the old status instead?

2020-08-19 13:38 UTC, TimothyHou commented
ok changes are made.
I noticed you changed the prompt message from 'Why do you want to change status?' to 'Click submit if you confirm the change of prayer status.' The intention is to ask the user to write updates in the prayer request field. 

e.g.
> Please pray for my exam

Change status from Active to Completed

> Please pray for my exam
> Edit: Thanks for praying! The exam went smoothly

Something like that. So we can improve user experience.

So is it ok if i change back? Or at least change to something more user friendly?

2020-08-20 01:04 UTC, Jonathanlau92 commented
@TimothyHou the prompt will be different for different status changes? ohh cause i was abit confused when i need to confirm my edit haha

2020-08-20 03:18 UTC, TimothyHou commented
Eh as long as the status change, then the prompt will be there hahaha. But anyway i think everyone will interpret the prompt differently. Think can just leave it as it is ba.

Let me know if you're ok with this PR! I will merge it once you confirm.

2020-08-21 15:52 UTC, merged